# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_VerifyTvdNr_rcpp_hello`)
}

#' Testing Verification function of TVD-Numbers
#'
#' An object of class simpleanimal is created where
#' the constructor calls a verification function.
#' This should verify that the specified TVD-Nr is
#' valid.
#'
#' @param psinputFile name of an input file name
#' @export verifyTvdNrMain
verifyTvdNrMain <- function(psinputFile) {
    invisible(.Call(`_VerifyTvdNr_verifyTvdNrMain`, psinputFile))
}

